#!/usr/bin/python
# -*-coding:utf-8 -*-

import paramiko


class SSHConnection(object):

    def __init__(self, host='169.254.1.32', port=22, username='root', pwd='123456'):
        self.host = host
        self.port = port
        self.username = username
        self.pwd = pwd
        self.__k = None

    def connect(self):
        transport = paramiko.Transport((self.host, self.port))
        transport.connect(username=self.username, password=self.pwd)
        self.__transport = transport

    def close(self):
        self.__transport.close()
        del self

    def upload(self, local_path, target_path):
        # file_name = self.create_file()
        sftp = paramiko.SFTPClient.from_transport(self.__transport)
        sftp.put(local_path, target_path)

    def download(self, remote_path, local_path):
        sftp = paramiko.SFTPClient.from_transport(self.__transport)
        sftp.get(remote_path, local_path)

    def cmd(self, command):
        ssh = paramiko.SSHClient()
        ssh._transport = self.__transport
        stdin, stdout, stderr = ssh.exec_command(command)
        result = stdout.read()
        print result
        return result


import time
from Configure.constant import SLOTS
ip_list = [32, 33, 34, 35]

for i in ip_list[:SLOTS]:
    rpc = SSHConnection(host='169.254.1.{}'.format(i))
    rpc.connect()
    rpc.cmd("date -s '@{}'".format(time.time()))
    rpc.close()

